### ISSUE TITLE
Error occurs when merging different flv models together.

### ISSUE THREAD

**Issue by OxxyLix** [Pear0533/FLVER_Editor#104]
"An error occurred while attempting to merge external FLVER with the current one". When I try to close the flver editor, it doesn't allow me to and gives me next "Index was out of range. Must be non-negative and less than the size of the collection. DS II SOFTS.

Problem doesn't happen when mergin 2 or 3 models, but when I try merging more than roughly 5-6, it starts to crumble

**Comment by Pear0533** [comment]
I wouldn't recommend using the merge feature, as it will be deprecated due to the existence of Aqua Model Tools, which allows you to export a FLVER file as an FBX, and import it into another one. I'll take a look at it when I can, but I can't promise anything.

**Comment by OxxyLix** [comment]
> I wouldn't recommend using the merge feature, as it will be deprecated due to the existence of Aqua Model Tools, which allows you to export a FLVER file as an FBX, and import it into another one. I'll take a look at it when I can, but I can't promise anything.

oh thx, didn't know about aqua model tools, will give that a try

**Comment by OxxyLix** [comment]
> I wouldn't recommend using the merge feature, as it will be deprecated due to the existence of Aqua Model Tools, which allows you to export a FLVER file as an FBX, and import it into another one. I'll take a look at it when I can, but I can't promise anything.

sorry man, can you help. I used aqua tools to export a map as an FBX, but I can't import it in the editor. Gives me next mistake - "10_31_00_00_map.fbx could not be read" "Error : external component has thrown an exception"

**Comment by Pear0533** [comment]
Would you be able to share the exported FBX file? It would help to debug what is going on here.

**Comment by OxxyLix** [comment]
> Would you be able to share the exported FBX file? It would help to debug what is going on here.

yeah man, one sec. I checked different fbx files, so no idea.

[Heide's tower the file.zip](https://github.com/Pear0533/FLVER_Editor/files/12694531/Heide.s.tower.the.file.zip)

**Comment by Pear0533** [comment]
This appears to be a memory limitation with FbxImporter, I would ask Avenger about this in Servername. Sorry I can't help more.

**Comment by OxxyLix** [comment]
> This appears to be a memory limitation with FbxImporter, I would ask Avenger about this in Servername. Sorry I can't help more.

hm ok, thx man
