### ISSUE TITLE
Delete associated material when a mesh is deleted and vice versa

### ISSUE THREAD

**Issue by char6s** [Pear0533/FLVER_Editor#106]
Mesh and material are linked, so wouldn't it be better to delete them together? 

For example, in V2.2, if I delete a mesh, the associated material remains in the materials tab, doing nothing. The same goes for mesh.

**Comment by Pear0533** [comment]
Not necessarily... there are plenty of cases where you would want to delete a mesh, but re-use its material elsewhere for other purposes through presets and the like. In any case, having an option to link them upon mesh deletion would be convenient, so I'll look into it with Natsu.
